version: "3.1"
services:

  api:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: python_employee_server
    restart: unless-stopped
    environment:
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - migrations
    env_file:
      - .env
    command: [
      "poetry", "run", "python", "-m", "app"
    ]
    ports:
      - "${API_PORT}:8080"

  db:
    image: postgres
    container_name: python_employee_postgresql
    restart: unless-stopped
    volumes:
      - ${POSTGRES_LOCAL_STORAGE}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"

  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    container_name: python_employee_migrations
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    env_file:
      - .env
    command: [
      "bash", "./scripts/wait-for-server.sh", "db:5432", "-t", "120",
      "--",
      "poetry", "run", "python", "-m", "scripts.migrate"
    ]
    depends_on:
      - db